version: '3.7'

services:
  namenode:
    build: namenode
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"

  datanode:
    build: datanode
    container_name: datanode
    hostname: datanode
    links:
      - namenode
    depends_on:
      - namenode

  spark-master:
    build: spark
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - spark-binaries:/opt/bitnami/spark

  spark-worker1:
    build: spark
    container_name: spark-worker1
    hostname: spark-worker1
    links:
      - spark-master
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=10g
  
  spark-worker2:
    build: spark
    container_name: spark-worker2
    hostname: spark-worker2
    links:
      - spark-master
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=10g

  jupyter:
    build: jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    links:
      - spark-master
    depends_on:
      - spark-master

  zeppelin:
    build: zeppelin
    container_name: zeppelin
    hostname: zeppelin
    volumes:
      - spark-binaries:/opt/bitnami/spark
    ports:
      - "8081:8080"
    links:
      - spark-master
    depends_on:
      - spark-master

volumes:
  spark-binaries: